DELIMITER $$

USE `valsys_prod` $$

DROP VIEW IF EXISTS `PROSPECT_VW_DTL_2` $$

CREATE ALGORITHM = UNDEFINED DEFINER = `root` @`%` SQL SECURITY DEFINER VIEW `PROSPECT_VW_DTL_2` AS 
SELECT 
  `PROSPECT`.`PROSPECT_ID` AS `PROSPECT_ID`,
  `PROSPECT`.`PROSPECT_NBR` AS `PROSPECT_NBR`,
  `PROSPECT`.`SALESC` AS `SALESC`,
  `PROSPECT`.`PROSPECT_TYPE` AS `PROSPECT_TYPE`,
  `PROSPECT`.`CATEGORY` AS `CATEGORY`,
  `PROSPECT`.`TITLE` AS `TITLE`,
  `PROSPECT`.`SALUTATION` AS `SALUTATION`,
  `PROSPECT`.`FIRST_NAME` AS `FIRST_NAME`,
  `PROSPECT`.`MIDDLE_NAME` AS `MIDDLE_NAME`,
  `PROSPECT`.`LAST_NAME` AS `LAST_NAME`,
  `PROSPECT`.`COMPANY_NAME` AS `COMPANY_NAME`,
  `PROSPECT`.`CONTACT_NAME` AS `CONTACT_NAME`,
  `PROSPECT`.`HOME_PHONE` AS `HOME_PHONE`,
  `PROSPECT`.`WORK_PHONE` AS `WORK_PHONE`,
  `PROSPECT`.`MOBILE_PHONE` AS `MOBILE_PHONE`,
  `PROSPECT`.`FAX_NBR` AS `FAX_NBR`,
  `PROSPECT`.`EMAIL` AS `EMAIL`,
  `PROSPECT`.`ALTERNATE_EMAIL` AS `ALTERNATE_EMAIL`,
  `PROSPECT`.`NOTES` AS `NOTES`,
  `PROSPECT`.`REF_CUST_ID` AS `REF_CUST_ID`,
  `PROSPECT`.`CREATED_BY` AS `CREATED_BY`,
  `PROSPECT`.`CREATED_DATE` AS `CREATED_DATE`,
  `PROSPECT`.`PLN_ID` AS `PLN_ID`,
  `PROSPECT`.`ID_TYPE` AS `ID_TYPE`,
  `PROSPECT`.`IDTYPE_NUMBER` AS `IDTYPE_NUMBER`,
  `PROSPECT`.`EXP_DATE` AS `EXP_DATE`,
  `PROSPECT`.`OCCUPATION` AS `OCCUPATION`,
  `PROSPECT`.`INCOME` AS `INCOME`,
  `PROSPECT`.`OPENTITY_ID` AS `OPENTITY_ID`,
  `PROSPECT`.`DTH_NOTE` AS `DTH_NOTE`,
  `PROSPECT`.`ADM_NOTE` AS `ADM_NOTE`,
  `PROSPECT`.`FORMN` AS `FORMN`,
  `PROSPECT`.`FBEDA` AS `FBEDA`,
  UPPER(`PROSPECT`.`statusep`) AS `STATUSEP`,
  `PROSPECT`.`FBEDABILLING_IDENTITY` AS `FBEDABILLING_IDENTITY`,
  `PROSPECT`.`FBEDABILLING_INSTALL` AS `FBEDABILLING_INSTALL`,
  `PROSPECT_ADDRESS`.`ADDRESS_TEMPLATE_ID` AS `ADDRESS_TEMPLATE_ID`,
  `PROSPECT_ADDRESS`.`STREET` AS `STREET`,
  `PROSPECT_ADDRESS`.`PROSPECT_ID_ICC` AS `PROSPECT_ID_ICC`,
  `PROSPECT_ADDRESS`.`HOUSE_NUMBER` AS `HOUSE_NUMBER`,
  `PROSPECT_ADDRESS`.`DIRECTION` AS `DIRECTION`,
  `PROSPECT_ADDRESS`.`LANDMARK` AS `LANDMARK`,
  `PROSPECT_ADDRESS`.`CLUSTER` AS `CLUSTER`,
  `PROSPECT_ADDRESS`.`AREA` AS `AREA`,
  `PROSPECT_ADDRESS`.`SUBDISTRICT` AS `SUBDISTRICT`,
  `PROSPECT_ADDRESS`.`DISTRICT` AS `DISTRICT`,
  `PROSPECT_ADDRESS`.`CITY` AS `CITY`,
  `PROSPECT_ADDRESS`.`PROVINCE` AS `PROVINCE`,
  `PROSPECT_ADDRESS`.`STATE` AS `STATE`,
  `PROSPECT_ADDRESS`.`COUNTRY` AS `COUNTRY`,
  `PROSPECT_ADDRESS`.`RT` AS `RT`,
  `PROSPECT_ADDRESS`.`RW` AS `RW`,
  `PROSPECT_ADDRESS`.`BUILDING_TYPE` AS `BUILDING_TYPE`,
  `PROSPECT_ADDRESS`.`BUILDING_ROOM_NUMBER` AS `BUILDING_ROOM_NUMBER`,
  `PROSPECT_ADDRESS`.`VALID_ADDR_ID` AS `VALID_ADDR_ID`,
  `PROSPECT_ADDRESS`.`POSTALCODE` AS `POSTALCODE`,
  `PROSPECT_ADDRESS`.`INSTALLATION_DIRECTION` AS `INSTALLATION_DIRECTION`,
  `PROSPECT_ADDRESS`.`INSTALLATION_LANDMARK` AS `INSTALLATION_LANDMARK`,
  `PROSPECT_ADDRESS`.`INSTALLATION_HOUSE_NUMBER` AS `INSTALLATION_HOUSE_NUMBER`,
  `PROSPECT_ADDRESS`.`INSTALLATION_HOUSE_RT` AS `INSTALLATION_HOUSE_RT`,
  `PROSPECT_ADDRESS`.`INSTALLATION_HOUSE_RW` AS `INSTALLATION_HOUSE_RW`,
  `PROSPECT_ADDRESS`.`BILLING_DIRECTION` AS `BILLING_DIRECTION`,
  `PROSPECT_ADDRESS`.`BILLING_LANDMARK` AS `BILLING_LANDMARK`,
  `PROSPECT_ADDRESS`.`NOTES` AS `NOTE_ADDR`,
  `PROSPECT_ADDRESS`.`INSTALLATION_ADDRESS` AS `INSTALLATION_ADDRESS`,
  `PROSPECT_ADDRESS`.`INSTALLATION_PROVINCE` AS `INSTALLATION_PROVINCE`,
  `PROSPECT_ADDRESS`.`INSTALLATION_CITY` AS `INSTALLATION_CITY`,
  `PROSPECT_ADDRESS`.`INSTALLATION_DISTRICT` AS `INSTALLATION_DISTRICT`,
  `PROSPECT_ADDRESS`.`INSTALLATION_SUBDISTRICT` AS `INSTALLATION_SUBDISTRICT`,
  `PROSPECT_ADDRESS`.`INSTALLATION_ZIPCODE` AS `INSTALLATION_ZIPCODE`,
  `PROSPECT_ADDRESS`.`BILLING_ADDRESS` AS `BILLING_ADDRESS`,
  `PROSPECT_ADDRESS`.`BILLING_PROVINCE` AS `BILLING_PROVINCE`,
  `PROSPECT_ADDRESS`.`BILLING_CITY` AS `BILLING_CITY`,
  `PROSPECT_ADDRESS`.`BILLING_DISTRICT` AS `BILLING_DISTRICT`,
  `PROSPECT_ADDRESS`.`BILLING_SUBDISTRICT` AS `BILLING_SUBDISTRICT`,
  `PROSPECT_ADDRESS`.`BILLING_ZIPCODE` AS `BILLING_ZIPCODE`,
  `PROSPECT_ADDRESS`.`BUILDING_STATUS` AS `BUILDING_STATUS`,
  `PROSPECT_ADDRESS`.`BILLING_HOUSE_NUMBER` AS `BILLING_HOUSE_NUMBER`,
  `PROSPECT_ADDRESS`.`BILLING_HOUSE_RT` AS `BILLING_HOUSE_RT`,
  `PROSPECT_ADDRESS`.`BILLING_HOUSE_RW` AS `BILLING_HOUSE_RW`,
  `PROSPECT`.`LONGITUDE` AS `LONGITUDE`,
  `PROSPECT`.`LATITUDE` AS `LATITUDE`,
  `PROSPECT_ADDITIONAL`.`EMPLOYEE_ID` AS `EMPLOYEE_ID`,
  `PROSPECT_ADDITIONAL`.`STORE_AREA` AS `STORE_AREA`,
  `PROSPECT_ADDITIONAL`.`BT_DK_LK` AS `BT_DK_LK`,
  `PROSPECT_ADDITIONAL`.`BT_BRANCH_OFFICE` AS `BT_BRANCH_OFFICE`,
  `PROSPECT_ADDITIONAL`.`BT_REGION_OFFICE` AS `BT_REGION_OFFICE`,
  `PROSPECT_ADDITIONAL`.`BT_TRANSPORTATION_FEE` AS `BT_TRANSPORTATION_FEE`,
  `PROSPECT_ADDITIONAL`.`TRANSPORTATION_FEE_FLAG` AS `TRANSPORTATION_FEE_FLAG`,
  `PROSPECT_ADDITIONAL`.`KET_TTD` AS `KET_TTD`,
  `PROSPECT_ADDITIONAL`.`KET_BEDA_ALAMAT` AS `KET_BEDA_ALAMAT`,
  `PROSPECT_ADDITIONAL`.`KET_IDENTITAS` AS `KET_IDENTITAS`,
  `PROSPECT_ADDITIONAL`.`KET_PEMILIKRUMAH` AS `KET_PEMILIKRUMAH`,
  `PROSPECT_ADDITIONAL`.`KET_CC` AS `KET_CC`,
  `PROSPECT_ADDITIONAL`.`KET_TAGIHAN` AS `KET_TAGIHAN`,
  `PROSPECT_ADDITIONAL`.`KET_PICKUPDANA` AS `KET_PICKUPDANA`,
  `PROSPECT_ADDITIONAL`.`INPUT_PICKUPDANA` AS `INPUT_PICKUPDANA`,
  `PROSPECT_ADDITIONAL`.`KET_SURATKUASA` AS `KET_SURATKUASA`,
  `PROSPECT_ADDITIONAL`.`KET_INSTANSI` AS `KET_INSTANSI`,
  `PROSPECT_ADDITIONAL`.`KET_PERNYATAANSEWA` AS `KET_PERNYATAANSEWA`,
  `PROSPECT_ADDITIONAL`.`KET_PERNYATAAN_MULTI_PELANGGAN` AS `KET_PERNYATAAN_MULTI_PELANGGAN`,
  `PROSPECT_ADDITIONAL`.`KET_PERNYATAAN_BUNDLE_INTERNET` AS `KET_PERNYATAAN_BUNDLE_INTERNET`,
  `PROSPECT_ADDITIONAL`.`EXTRA_MOBILE` AS `EXTRA_MOBILE`,
  `PROSPECT_ADDITIONAL`.`MARITAL_STATUS` AS `MARITAL_STATUS`,
  `PROSPECT_ADDITIONAL`.`PLACE_BIRTH` AS `PLACE_BIRTH`,
  `PROSPECT_ADDITIONAL`.`DATE_OF_BIRTH` AS `DATE_OF_BIRTH`,
  `PROSPECT_ADDITIONAL`.`TYPE_OF_WORK` AS `TYPE_OF_WORK`,
  `PROSPECT_ADDITIONAL`.`FAM_STRUCTURE` AS `FAM_STRUCTURE`,
  `PROSPECT_ADDITIONAL`.`RELIGION` AS `RELIGION`,
  `PROSPECT_ADDITIONAL`.`EDUCATION_LEVEL` AS `EDUCATION_LEVEL`,
  `PROSPECT_ADDITIONAL`.`ID_NUMBER` AS `ID_NUMBER`,
  `PROSPECT_ADDITIONAL`.`SGS_NUMBER` AS `SGS_NUMBER`,
  `PROSPECT_ADDITIONAL`.`SGS_NAME` AS `SGS_NAME`,
  `PROSPECT_ADDITIONAL`.`SGS_RELATION` AS `SGS_RELATION`,
  `PROSPECT_ADDITIONAL`.`EC_PHONE` AS `EC_PHONE`,
  `PROSPECT_ADDITIONAL`.`EC_RELATION` AS `EC_RELATION`,
  `PROSPECT_ADDITIONAL`.`EC_NAME` AS `EC_NAME`,
  `PROSPECT_ADDITIONAL`.`EC_ADDR` AS `EC_ADDR`,
  `PROSPECT_ADDITIONAL`.`GENDER` AS `GENDER`,
  `PROSPECT_ADDITIONAL`.`MULTI_CUST` AS `MULTI_CUST`,
  `PROSPECT_ADDITIONAL`.`MULTI_DSD` AS `MULTI_DSD`,
  `PROSPECT_ADDITIONAL`.`AMOUNT_DSD` AS `AMOUNT_DSD`,
  `PROSPECT_ADDITIONAL`.`STATUS_HW` AS `STATUS_HW`,
  `PROSPECT_ADDITIONAL`.`SFL` AS `SFL`,
  `PROSPECT_ADDITIONAL`.`SCHEDULE_DATE` AS `SCHEDULE_DATE`,
  `PROSPECT_ADDITIONAL`.`CLOSING_DATE` AS `CLOSING_DATE`,
  `PROSPECT_ADDITIONAL`.`EMPLOYEE_NIK` AS `EMPLOYEE_NIK`,
  `PROSPECT_ADDITIONAL`.`EMP_COMPANY` AS `EMP_COMPANY`,
  `PROSPECT_ADDITIONAL`.`EMP_POSITION` AS `EMP_POSITION`,
  `PROSPECT_ADDITIONAL`.`VERIFICATION_DATE` AS `VERIFICATION_DATE`,
  `PROSPECT_ADDITIONAL`.`VERIFICATION_PERIOD` AS `VERIFICATION_PERIOD`,
  `PROSPECT_ADDITIONAL`.`AREA_PEMASANGAN` AS `AREA_PEMASANGAN`,
  `PROSPECT_ADDITIONAL`.`INSTALLATION_DATE` AS `INSTALLATION_DATE`,
  `PROSPECT_ADDITIONAL`.`INSTALLATION_TIME` AS `INSTALLATION_TIME`,
  `PROSPECT_ADDITIONAL`.`CONFIRMATION_TIME_START` AS `CONFIRMATION_TIME_START`,
  `PROSPECT_ADDITIONAL`.`CONFIRMATION_TIME_END` AS `CONFIRMATION_TIME_END`,
  `PROSPECT_ADDITIONAL`.`NIK_SALES` AS `NIK_SALES`,
  `PROSPECT_ADDITIONAL`.`NAME_SALES` AS `NAME_SALES`,
  `PROSPECT_ADDITIONAL`.`SALES_CODE` AS `SALES_CODE`,
  `PROSPECT_ADDITIONAL`.`HEAD_BRANCH` AS `HEAD_BRANCH`,
  `PROSPECT_ADDITIONAL`.`DIFFERENT_CAUSE` AS `DIFFERENT_CAUSE`,
  `PROSPECT_ADDITIONAL`.`SCORE_CARD` AS `SCORE_CARD`,
  `PROSPECT_COST`.`INSTALLATION_COST` AS `INSTALLATION_COST`,
  `PROSPECT_COST`.`COST_PACKAGE` AS `COST_PACKAGE`,
  `PROSPECT_COST`.`ALACARTE_COST` AS `ALACARTE_COST`,
  `PROSPECT_COST`.`INTERNET_COST` AS `INTERNET_COST`,
  `PROSPECT_COST`.`PROMO_COST` AS `PROMO_COST`,
  `PROSPECT_COST`.`TOTAL_COST` AS `TOTAL_COST`,
  `PROSPECT_COST`.`BELI_PUTUS_COST` AS `BELI_PUTUS_COST`,
  `PROSPECT_COST`.`DEC_HD_COST` AS `DEC_HD_COST`,
  `PROSPECT_PAYMENT`.`PAYMENT_NBR` AS `PAYMENT_NBR`,
  `PROSPECT_PAYMENT`.`BANK_ACCOUNT_NO` AS `PAYMENT_BANK_ACCOUNT_NO`,
  `PROSPECT_PAYMENT`.`PAYMENT_DATE` AS `PAYMENT_DATE`,
  `PROSPECT_PAYMENT`.`PARTICULARS` AS `PARTICULARS`,
  `PROSPECT_PAYMENT`.`PAYMENT_MODE` AS `PAYMENT_MODE`,
  `PROSPECT_PAYMENT`.`PAYMENT_MODE_DETAIL_NO` AS `PAYMENT_MODE_DETAIL_NO`,
  `PROSPECT_PAYMENT`.`CURRENCY_CODE` AS `CURRENCY_CODE`,
  `PROSPECT_PAYMENT`.`AMOUNT` AS `AMOUNT`,
  `PROSPECT_PAYMENT`.`PAYMENT_DIRECT_DEBIT` AS `PAYMENT_DIRECT_DEBIT`,
  `PROSPECT_PAYMENT`.`RECEIPT_NBR` AS `RECEIPT_NBR`,
  `PROSPECT_PAYMENT`.`RECEIPT_DATE` AS `RECEIPT_DATE`,
  `PROSPECT_PAYMENT`.`STATUS` AS `PAYMNT_STATUS`,
  `PROSPECT_PAYMENT`.`COLLECTED_BY_TYPE` AS `COLLECTED_BY_TYPE`,
  `PROSPECT_PAYMENT`.`COLLECTED_BY` AS `COLLECTED_BY`,
  `PROSPECT_PAYMENT`.`APPROVE_DATE` AS `APPROVE_DATE`,
  `PROSPECT_PAYMENT`.`CANCEL_DATE` AS `CANCEL_DATE`,
  `PROSPECT_PAYMENT`.`CANCEL_NOTES` AS `CANCEL_NOTES`,
  `PROSPECT_PAYMENT`.`CANCEL_REASON` AS `CANCEL_REASON`,
  `PROSPECT_PAYMENT`.`NOTES` AS `PAYMENT_NOTES`,
  `PROSPECT_PAYMENT`.`BANK_NAME` AS `PAYMENT_BANK_NAME`,
  `PROSPECT_PAYMENT`.`ACCOUNT_NAME` AS `PAYMENT_ACCOUNT_NAME`,
  `PROSPECT_PAYMENT`.`CARD_TYPE` AS `PAYMENT_CARD_TYPE`,
  `PROSPECT_PAYMENT`.`CARD_NUMBER` AS `PAYMENT_CARD_NUMBER`,
  `PROSPECT_PAYMENT`.`EXP_DATE` AS `PAYMENT_EXP_DATE`,
  `PROSPECT_PAYMENT`.`PAYMENT_TYPE` AS `PAYMENT_TYPE`,
  `OPERATIONAL_ENTITY_VIEW`.`entity_code` AS `entity_code`,
  `OPERATIONAL_ENTITY_VIEW`.`entity_type` AS `entity_type`,
  `OPERATIONAL_ENTITY_VIEW`.`entity_name` AS `entity_name`,
  `OPERATIONAL_ENTITY_VIEW`.`branch` AS `branch`,
  `OPERATIONAL_ENTITY_VIEW`.`sales_channel` AS `sales_channel` 
FROM
  (
    (
      (
        (
          (
            `PROSPECT` 
            LEFT JOIN `PROSPECT_ADDRESS` 
              ON (
                (
                  `PROSPECT`.`PROSPECT_ID` = `PROSPECT_ADDRESS`.`PROSPECT_ID`
                )
              )
          ) 
          LEFT JOIN `PROSPECT_ADDITIONAL` 
            ON (
              (
                `PROSPECT`.`PROSPECT_ID` = `PROSPECT_ADDITIONAL`.`PROSPECT_ID`
              )
            )
        ) 
        LEFT JOIN `PROSPECT_COST` 
          ON (
            (
              `PROSPECT`.`PROSPECT_ID` = `PROSPECT_COST`.`PROSPECT_ID`
            )
          )
      ) 
      LEFT JOIN `PROSPECT_PAYMENT` 
        ON (
          (
            `PROSPECT`.`PROSPECT_ID` = `PROSPECT_PAYMENT`.`PROSPECT_ID`
          )
        )
    ) 
    LEFT JOIN `OPERATIONAL_ENTITY_VIEW` 
      ON (
        (
          `PROSPECT`.`OPENTITY_ID` = `OPERATIONAL_ENTITY_VIEW`.`entity_id`
        )
      )
  ) $$

DELIMITER ;

