DELIMITER $$

USE `valsys_prod`$$

DROP TRIGGER /*!50032 IF EXISTS */ `TRG_PROSPECT_PACKAGE_ORDER`$$

CREATE
    /*!50017 DEFINER = 'root'@'%' */
    TRIGGER `TRG_PROSPECT_PACKAGE_ORDER` BEFORE UPDATE ON `PROSPECT_PACKAGE_ORDER` 
    FOR EACH ROW BEGIN
    DECLARE gUSER VARCHAR(50);
    DECLARE vBrandNameNew VARCHAR(50);
    DECLARE vBrandNameOld  VARCHAR(50);
    DECLARE vPromoCodeNew  VARCHAR(50);
    DECLARE vPromoCodeOld  VARCHAR(50);
    DECLARE vBillingFDescNew  VARCHAR(50);
    DECLARE vBillingFDescOld  VARCHAR(50);
    
    
     IF NEW.`LAST_UPD_BY` = '' THEN
    
    SET gUSER = gUSER;
  ELSE
    SET gUSER = NEW.`LAST_UPD_BY`;
  END IF;    
  
    IF NEW.`BRAND` <> OLD.`BRAND` THEN
    SELECT BRAND_NAME INTO vBrandNameNew FROM SMS_M_BRAND WHERE NEW.`BRAND`  = BRAND_ID ;
    SELECT BRAND_NAME INTO vBrandNameOld FROM SMS_M_BRAND WHERE OLD.`BRAND`  = BRAND_ID;
    INSERT INTO LOG_PROSPECT_UPDATE 
    (`PROSPECT_ID`, `TABLE_VALSYS`, `FIELD`, `VALUE_BEFORE`, `VALUE_AFTER`, `UPDATE_BY`,`UPDATE_DATE`)
    VALUES
    (OLD.`PROSPECT_ID`, 'PROSPECT_PACKAGE_ORDER', 'BRAND', vBrandNameOld, vBrandNameNew, gUSER,NOW());
  END IF;
  IF NEW.`STATUS` <> OLD.`STATUS` THEN
    INSERT INTO LOG_PROSPECT_UPDATE 
    (`PROSPECT_ID`, `TABLE_VALSYS`, `FIELD`, `VALUE_BEFORE`, `VALUE_AFTER`, `UPDATE_BY`,`UPDATE_DATE`)
    VALUES
    (OLD.`PROSPECT_ID`, 'PROSPECT_PACKAGE_ORDER', 'STATUS', OLD.`STATUS`, NEW.`STATUS`, gUSER,NOW());
  END IF;
  IF NEW.`AVAILABLE_PROMO` <> OLD.`AVAILABLE_PROMO` THEN
    SELECT PROMOTION_CODE INTO vPromoCodeNew FROM M_PROMOTION WHERE PROMOTION_ID =  NEW.`AVAILABLE_PROMO`;
    SELECT PROMOTION_CODE INTO vPromoCodeOld FROM M_PROMOTION WHERE PROMOTION_ID =  OLD.`AVAILABLE_PROMO`;
    INSERT INTO LOG_PROSPECT_UPDATE 
    (`PROSPECT_ID`, `TABLE_VALSYS`, `FIELD`, `VALUE_BEFORE`, `VALUE_AFTER`, `UPDATE_BY`,`UPDATE_DATE`)
    VALUES
    (OLD.`PROSPECT_ID`, 'PROSPECT_PACKAGE_ORDER', 'AVAILABLE_PROMO', vPromoCodeOld, vPromoCodeNew, gUSER,NOW());
  END IF;
  IF NEW.`BILLING_FREQUENCY` <> OLD.`BILLING_FREQUENCY` THEN
    SELECT DESC_BILLINGF INTO vBillingFDescNew FROM MASTER_BILLING_F WHERE ID_BILLINGF = NEW.`BILLING_FREQUENCY` ;
    SELECT DESC_BILLINGF INTO vBillingFDescOld FROM MASTER_BILLING_F WHERE ID_BILLINGF = OLD.`BILLING_FREQUENCY` ;    
    INSERT INTO LOG_PROSPECT_UPDATE 
    (`PROSPECT_ID`, `TABLE_VALSYS`, `FIELD`, `VALUE_BEFORE`, `VALUE_AFTER`, `UPDATE_BY`,`UPDATE_DATE`)
    VALUES
    (OLD.`PROSPECT_ID`, 'PROSPECT_PACKAGE_ORDER', 'BILLING_FREQUENCY', vBillingFDescOld, vBillingFDescNew, gUSER,NOW());
  END IF;
     
     
     
    
	
 
END;
$$

DELIMITER ;