DELIMITER $$

USE `valsys_prod`$$

DROP TRIGGER /*!50032 IF EXISTS */ `TRG_PROSPECT_PRODUCT_before_update`$$

CREATE
    /*!50017 DEFINER = 'root'@'%' */
    TRIGGER `TRG_PROSPECT_PRODUCT_before_update` BEFORE UPDATE ON `PROSPECT_PRODUCT` 
    FOR EACH ROW BEGIN
  DECLARE gUSER VARCHAR(50);
  
  IF NEW.`PROSPECT_PRODUCT_INSERT_BY` = '' THEN
    
    SET gUSER = 'SYSTEM';
  ELSE
    SET gUSER = NEW.`PROSPECT_PRODUCT_INSERT_BY`;
  END IF;
  
  IF NEW.`PRODUCT_ID` <> OLD.`PRODUCT_ID` THEN
    INSERT INTO LOG_PROSPECT_UPDATE 
    (`PROSPECT_NBR`, `TABLE_VALSYS`, `FIELD`, `VALUE_BEFORE`, `VALUE_AFTER`, `UPDATE_BY`)
    VALUES
    (OLD.`PROSPECT_ID`, 'PROSPECT_PRODUCT', 'PRODUCT_ID', OLD.`PRODUCT_ID`, NEW.`PRODUCT_ID`, gUSER);
  END IF;
  IF NEW.`PRODUCT_CATEGORY` <> OLD.`PRODUCT_CATEGORY` THEN
    INSERT INTO LOG_PROSPECT_UPDATE 
    (`PROSPECT_NBR`, `TABLE_VALSYS`, `FIELD`, `VALUE_BEFORE`, `VALUE_AFTER`, `UPDATE_BY`)
    VALUES
    (OLD.`PROSPECT_ID`, 'PROSPECT_PRODUCT', 'PRODUCT_CATEGORY', OLD.`PRODUCT_CATEGORY`, NEW.`PRODUCT_CATEGORY`, gUSER);
  END IF;
  IF NEW.`PRODUCT_TYPE` <> OLD.`PRODUCT_TYPE` THEN
    INSERT INTO LOG_PROSPECT_UPDATE 
    (`PROSPECT_NBR`, `TABLE_VALSYS`, `FIELD`, `VALUE_BEFORE`, `VALUE_AFTER`, `UPDATE_BY`)
    VALUES
    (OLD.`PROSPECT_ID`, 'PROSPECT_PRODUCT', 'PRODUCT_TYPE', OLD.`PRODUCT_TYPE`, NEW.`PRODUCT_TYPE`, gUSER);
  END IF;
END;
$$

DELIMITER ;